### ISSUE TITLE
maximum limit crwaling reddit data (Not an issue)

### ISSUE THREAD

**Issue by nb9887** [socius-org/RedditHarbor#15]
Thank you for the great code.
Successfully downloaded and using it right now, I do appreicate that, by any chance, do you know how many data we can crawl from reddit using your source code? (maximum limit) 

and can i parse more than 2 or 3 parameters just like the code below?
I haven't get to chance the analyze the code yet though

subreddits = ["bitcoin", "ethereum", "solana"]
sort_types = ["hot", "top", "new", "rising"]
collect.subreddit_submission(subreddits, sort_types, limit=1)

**Comment by nick-sh-oh** [comment]
Hi @nb9887,

Thank you for your encouraging words! I'm glad you find the project helpful.

While there are **no specific limits on the number of submissions, comments, or user data that you can crawl, the Reddit Data API imposes a QPM (queries per minute) limit of 100 per OAuth client ID.** 

And yes, you can parse more than 2-3 parameters! Regarding the code you provided, it is likely to collect 1 submission for each of the specified sort types (`new`, `hot`, `top`, and `rising`) across the three subreddits you mentioned. Therefore, the total number of submissions collected would be ~12 (if the sorted submissions do not overlap).

p.s It seems that you are interested in collecting crypto-related subreddits - we've actually curated a collection of crypto-related subreddits within `redditharbor.utils.subreddit_collections` (see https://github.com/socius-org/RedditHarbor/blob/main/redditharbor/utils/subreddit_collections.py). Just in case you are interested, you can access and utilise these subreddits in your code as follows:

```python
from redditharbor.utils import subreddit_collections

subreddits = subreddit_collections.r_Crypto
```
