### ISSUE TITLE
Trouble at the installation step

### ISSUE THREAD

**Issue by jcnycdoc** [socius-org/RedditHarbor#16]
When I enter "pip install --upgrade redditharbor" into the terminal, I receive the message "zsh: command not found: pip"
![Screen Shot 2024-04-25 at 12 07 40 PM](https://github.com/socius-org/RedditHarbor/assets/168108052/a9ace94a-5cac-44ef-a01b-46ac8db0136e)

**Comment by nick-sh-oh** [comment]
Hey @jcnycdoc, 

Sorry for delay in replying on your enquiry. 

Here is a step-by-step instructions that may work for you

# Before you install pip

Check which version of python is running on your Mac OS. 

1. In your terminal, run `python --version`
2. If Python is installed, you will see a message telling you the version. Or if it’s not installed, you will see command not found: python. 
3. If Python is not installed, you have to install [Python for Mac OS](https://www.python.org/downloads/macos/). Install Stable releases, not pre-releases. 

# After Installing Python 

1. In your terminal, run `python -m ensurepip`
2. This will install `pip`. 

This should allow you to run `pip install --upgrade redditharbor`! Let me know if you have any further questions, or still facing some issues.
