### ISSUE TITLE
Backslash in download path is not platform-independent

### ISSUE THREAD

**Issue by anyhannah** [socius-org/RedditHarbor#17]
### What's expected to happen
**submission.csv** with the collected Reddit data should be created in the specified folder **data/** when you run `download.to_csv()`.

### What happened instead
Depending on the format of `file_path`, a file named **data\submission.csv** is created in the current directory, or **\submission.csv** is created in **data/**.
<img width="154" alt="Screen Shot 2024-05-14 at 3 55 26 PM" src="https://github.com/socius-org/RedditHarbor/assets/19615539/278111d6-02b2-433f-bf2a-146dacc667c5">

### Code to reproduce the bug
Assuming you have `supabase_client` and `DB_CONFIG` properly set up,

the former case can be reproduced by
```
from redditharbor.utils import download

download = download.submission(supabase_client, DB_CONFIG["submission"])
download.to_csv(columns="all", file_name="submission", file_path="data/")
```

and the latter one by
```
from redditharbor.utils import download

download = download.submission(supabase_client, DB_CONFIG["submission"])
download.to_csv(columns="all", file_name="submission", file_path="data")
```

### A solution I can think of
The backslash in the path format `{save_file_path}\{file_name}` is not a valid character for cross-platform names, or at least it won't serve the intended purpose on macOS. Why not use a platform-neutral implementation, like ``os.path.join(f"{file_path}", f"{file_name}")`` or ``pathlib``?

**Comment by nick-sh-oh** [comment]
Hey @anyhannah, 

First off, thank you so much for taking the time to review the code and provide the suggestion. Appreciate you pointing out the potential issue with the platform-specific implementation! 

If you're willing to contribute your proposed solution directly by opening a pull request with your changes, that would be superb. However, if you don't have the time, no pressure at all. If that's the case, I'm happy to implement it myself, but I always want to ensure proper attribution for who suggested the improvement.

Either way, thank you again for your feedback!
