### ISSUE TITLE
RedditHarbor isnt collecting any submissions from a specific subreddit

### ISSUE THREAD

**Issue by adamczernus** [socius-org/RedditHarbor#19]
Hello, 

I am trying to pull posts with a keyword from the "Nootropics" subreddit, but it always returns with 0 submission data. Using the same code, I can get posts from all other subreddits. I know that r/nootropics is labeled as NSFW. Is there something that needs to be done differently to collect this?

Thank you,
Adam

**Comment by nick-sh-oh** [comment]
Hi @adamczernus,

Thank you for raising this issue. It's the first time I've encountered questions related to NSFW submissions, and I appreciate you bringing it! 

Based on the conversation I had (which was last week), access to NSFW content via the API seems to be restricted approximately a year ago. However, to provide a more definitive answer, I'll investigate this matter further and get back to you.

**Comment by adamczernus** [comment]
Hi @nick-sh-oh, thanks for the quick response. That would make sense. I collected data from that subreddit within the past year, but if Reddit restricts users from collecting this data I wont collect it.

**Comment by nick-sh-oh** [comment]
Hi @adamczernus - Being honest, I understand the importance of respecting Reddit's terms and conditions, but I also believe it's crucial for Reddit to support public research efforts. 

If you're still interested in gathering data from r/nootropics, I'm happy to explore alternative methods with you. (After all, I am here to assist researchers who face challenges in collecting and utilising data!)
