### ISSUE TITLE
Request for Enhanced User Sampling Methods for Diverse and Dense Social Network Analysis

### ISSUE THREAD

**Issue by vivrdprasanna** [socius-org/RedditHarbor#3]
I am reaching out to suggest an enhancement to the RedditHarbor tool, aimed at improving the methodology for constructing social networks on Reddit. My objective is to develop a network that is both densely connected and represents a broad range of communities. From my own experimentation, random sampling often results in a sparse network, and focusing on active users tends to skew the data towards specific communities.

As such, a feature that ensures a diverse representation of communities in the sample would be highly beneficial. Such improvements would not only serve my needs but also enhance the utility of RedditHarbor for users interested in a comprehensive analysis of social interactions on Reddit. Thank you for considering this suggestion, and I look forward to any developments in this area.

Thank you!

**Comment by nick-sh-oh** [comment]
The current version of RedditHarbor is somewhat naive anyways, so I was thinking of refactoring the repo. Perhaps sharing you with the future refactoring sketch may help you. Currently on top of my head, it will look like: 

```
utils/
|-- diversity_score.py: Calculating and sorting users by diversity score. 

collect/
|-- user.py
|---- from_submission: Function that collects user data from submission(s) and its comments. 
|---- from_subreddit: Function that collects user data active in subreddit(s). Only submissions. 
|-- submission.py
|---- from_user: Function that collects submission data from user(s)
|---- from subreddit : Function that collects submission data in subreddit(s) 
|-- comment.py 
|---- from_user: Function that collects comment data from user(s)
|---- from_subreddit: Function that collects comment data of submissions in subreddit(s) 
|-- subreddit.py 
|---- submission: Function that collects submission and user data from subreddit(s) 
|---- comment: Function that collects comment and user data from subreddit(s) 
```

**Comment by vivrdprasanna** [comment]
Thank you for the thoughtful response to my suggestion! This approach you mention indeed seems promising and aligns well with the objective of creating a more comprehensive and representative social network. 

One thought I had - while a diversity score is a strong starting point, incorporating a weighting mechanism might be beneficial. This could account for the level of engagement a user has in each community. For example, a user who is highly active in several communities could be given a higher score than someone who merely makes occasional posts across many subreddits. This would help in identifying not just the breadth of a user's community engagement but also the depth. Any thoughts? I imagine this would be more computationally intensive as it would involve tracking both frequency of posts as opposed to just the posts' / comments' existence. 

Thank you again for your time and dedication to improving RedditHarbor!

**Comment by nick-sh-oh** [comment]
Hi @vivrdprasanna! 

If I understand correctly: 

### 1. Breadth-Only Diversity Score:

The breadth-only diversity score measures the ratio of the number of unique communities a user engages with to the total number of posts or comments. It doesn't consider the depth of engagement.

$D_{\text{breadth}} = \frac{\text{Number of Unique Communities}}{\text{Total Number of Posts or Comments}}$

### 2. Weighted Diversity Score:

The weighted diversity score incorporates a weighting mechanism to account for the level of engagement a user has in each community. This provides a more nuanced assessment by considering both breadth and depth.

$D_{\text{weighted}} = \frac{\sum_{i} (\text{Weight}_i \times \text{Posts or Comments in Community}_i)}{\text{Total Number of Posts or Comments}}$

Here:
- $i$ represents each unique community.
- ${Weight}_i$ is the weight assigned to $community_i$. (I assume we can use either linear scaling or logarithmic scaling. If we use linear scaling, 
- $\text{Posts or Comments in Community}_i$ is the number of posts or comments the user made in $community_i$.
- The sum is taken over all unique communities in which the user has engaged.

Is this correct? If I was, I have one question related to calculating the ${Weight}_i$. Between linear scaling and logarithmic scaling, which one should will you choose? Should we actually try out both? 

### 1. Linear Scaling 

$w_i = \frac{\text{Engagement in Community}_i}{\text{Total Engagement Across All Communities}}$

### 2. Logarithmic Scaling 

$w_i = \log(\text{Engagement in Community}_i + 1)$

**Comment by vivrdprasanna** [comment]
Hello, 

Thanks for the exploring these diversity scoring methods! Regarding the choice between linear and logarithmic scaling: correct me if I'm wrong, but I feel the linear scaling method provides an intuitive approach where the weight directly mirrors the level of activity. This method is particularly useful when we aim to reflect the exact extent of a user's participation in each community.  On the other hand, by applying a logarithmic function, we can ensure that users with a more balanced participation across multiple communities are not overshadowed by those heavily active in fewer communities. 

Given this, I feel that it would be beneficial to first implement the linear scaling to identify highly active members within communities, as it makes sense that these users would have a larger influence on the network structure. If it turns out that we need to be able to understand broader community engagement patterns, logarithmic scaling can be something we pivot to.

**Comment by vivrdprasanna** [comment]
Hellom

Thank you for the update on the RedditHarbor's transformation into the redditharbor Python package. This is fantastic news, and I appreciate the effort to make it more accessible and user-friendly!

I'll start gathering the data and keep you updated on the progress. If any questions or challenges arise, I'll reach out promptly. It's really exciting to see the project advancing and I'm looking forward to contributing to its success!
