### ISSUE TITLE
Collecting image data from subreddit

### ISSUE THREAD

**Issue by adstephan** [socius-org/RedditHarbor#4]
Hello! Thank you for creating the RedditHarbor tool. I am very new to collecting Reddit data and am wondering if this tool can be used to collect only image data (just the images posted in a subreddit). Thanks for your help.

**Comment by nick-sh-oh** [comment]
Hi @adstephan, 

Thanks for your inquiry! 

TL;DR: You can collect image data only. 

Do you want to download image as json (image urls), or as jpeg?

**Comment by adstephan** [comment]
I'm interested in downloading the jpeg files, thanks!

**Comment by nick-sh-oh** [comment]
No problem! Will let you know as soon as such functionality is added.

**Comment by nick-sh-oh** [comment]
Hi @adstephan!

Your requested feature has been added! By following the outlined process below, you'll be able to effortlessly download jpg and png files from your preferred subreddits.

### 1. Collect Submission Data
Refer to the [Getting Started](https://github.com/socius-org/RedditHarbor/?tab=readme-ov-file#getting-started) and [Collect Submissions from Subreddits](https://github.com/socius-org/RedditHarbor/?tab=readme-ov-file#data-collection) sections to initiate the submission data collection.

### 2. Download jpg and png Files from the Submission Data
After collecting the submissions, execute the following Python script:

```python
import redditharbor.login as login 
from redditharbor.utils import download

supabase_client = login.supabase()
download = download.submission(supabase_client=supabase_client, db_name="<your-submission-db-name>")
download.to_img()
```

This script will automatically generate a folder named "submission_exports" and save all image files as jpg or png. 

If you also need to download video files or have any further inquiries, feel free to leave a comment! 

*P.S. I personally tested the `download.to_img()` functionality. When processing a database with 5,000 rows, it took approximately 5 minutes to download 1,073 image files contained within that database. The terminal output during the process is displayed below*:

<img width="778" alt="image" src="https://github.com/socius-org/RedditHarbor/assets/130935698/4e2d1e3f-a19c-46bb-a6df-2bee0f0e0c35">
