### ISSUE TITLE
Keyword Search? 

### ISSUE THREAD

**Issue by hw016** [socius-org/RedditHarbor#6]
Hello there!

I've reviewed the README.md file, but I'm a bit uncertain about whether the ability to collect submissions from specific subreddits based on keywords is a feature. Could you clarify if this functionality is available?

**Comment by nick-sh-oh** [comment]
Hi @hw016 

That's actually a key feature - Thanks for the suggestion. I will be working on such functionality shortly.

**Comment by nick-sh-oh** [comment]
The feature has been just added! Please upgrade redditharbor to its newest version, and if you have any questions, let me know.
