### ISSUE TITLE
Collecting queried submission comments and queried comments 

### ISSUE THREAD

**Issue by adamczernus** [socius-org/RedditHarbor#8]
Hello,

I've managed to gather submissions from subreddits using targeted keywords, but I hope to also collect the comments users have submitted under the initial collected submission in some structured way. Is it possible to collect the comments with a queried submission? 

Additionally, is there any way to collect comments with a keyword like I have for submissions? 

I appreciate you taking the time to read my message! 

Thank you

**Comment by nick-sh-oh** [comment]
Hi @adamczernus!

Your requested feature has been added! Regarding your additional question, Reddit API does not currently support collecting comments based on specific queries. 

Below is a guide on how to collect comments from the submissions you've gathered using targeted keywords.

### 1. Upgrade `redditharbor` to the Latest Version

Ensure you have the latest version of `redditharbor` installed by running the following command:

```python
pip install --upgrade redditharbor
```

### 2. Collect Comments Based on Submissions

#### 2.1 Fetch Submission IDs

First, you need to fetch the submission IDs from your Supabase database. Here's how you can do it:

```python
from redditharbor.utils import fetch 

fetch_submission = fetch.submission(supabase_client=supabase_client, db_name=db_config["submission"])
submission_ids = fetch_submission.id(limit=None) # Set limit=None to fetch all submission IDs
```

#### 2.2 Collect Comments 

Based on the `submission_ids` you can now collect comments. 

```python
from redditharbor.dock.pipeline import collect 

collect.comment_from_submission(submission_ids=submission_ids, level=1) # Set level=None to collect entire comments
```
Please note that the `level` parameter in the `collect.comment_from_submission` function determines the depth of comments to collect. Setting it to 1 collects only top-level comments, while setting it to 2 collects top-level comments and their replies. Set it to None to collect all comments and replies.
