### ISSUE TITLE
SSL Ceritification Verification Error

### ISSUE THREAD

**Issue by adamczernus** [socius-org/RedditHarbor#9]
Hello,

I have tried to use the new functionality to gather comment threads from submissions I have gathered. I am running into the following error:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate 
in certificate chain (_ssl.c:1129)

Below is the code I am running:
<img width="1251" alt="Screen Shot 2024-02-22 at 4 13 34 PM" src="https://github.com/socius-org/RedditHarbor/assets/160266891/80f62f41-3788-4f24-bde4-f55d240bc38b">

I appreciate the help,
Adam

**Comment by nick-sh-oh** [comment]
Hi @adamczernus,

Could you please provide a screenshot of the error message displayed in your terminal? This will help us better understand and troubleshoot the issue you're experiencing.

**Comment by adamczernus** [comment]
@nick-sh-oh 
<img width="747" alt="Screen Shot 2024-02-22 at 4 26 55 PM" src="https://github.com/socius-org/RedditHarbor/assets/160266891/0c9b605d-6da1-4c95-a577-43c1d34564a0">
<img width="745" alt="Screen Shot 2024-02-22 at 4 27 43 PM" src="https://github.com/socius-org/RedditHarbor/assets/160266891/86be2eca-346a-452e-abd3-12329b76d2a4">

**Comment by nick-sh-oh** [comment]
Thanks for providing the screenshot @adamczernus! 

To pinpoint the exact line causing the SSLCertVerificationError, could you please follow these steps:

**1.** Run `login.reddit()` alone and check if it prints "Connected to Reddit successfully" or the error message.
```python
import redditharbor.login as login
login.reddit()
```

**2.** Run `login.supabase()` alone and check if it prints "Connected to Supabase successfully" or the error message.
```python
import redditharbor.login as login
login.supabase()
```

**3.** Run `fetch_submission.id()` alone and check if it prints a list with some submission ID or the error message.
```python
import redditharbor.login as login
from redditharbor.utils import fetch

reddit_client = login.reddit()
supabase_client = login.supabase()
fetch_submission = fetch.submission(supabase_client=supabase_client, db_name=db_config["submission"])
print(fetch_submission.id(limit=1))
```

Please let me know at which step you encounter the error message. This will help us isolate the issue and provide a targeted solution.

**Comment by adamczernus** [comment]
Hello @nick-sh-oh ,

Thank you for the quick response!

I ran all of the commands successfully as seen below:

<img width="600" alt="Screen Shot 2024-02-24 at 8 54 27 PM" src="https://github.com/socius-org/RedditHarbor/assets/160266891/8d2f2357-d32a-446a-87ff-131facc0d5ec">

I did not change any of the original code which presented the SSLcertVerificationError and reran which gave me a new error:

<img width="794" alt="Screen Shot 2024-02-24 at 8 57 11 PM" src="https://github.com/socius-org/RedditHarbor/assets/160266891/bdcaaa7d-8d40-4f37-a6c8-ebb6de3284d1">

Per the documentation, it does not seem like I am missing any arguments. Do you know what this may be?

Thank you,
Adam

**Comment by nick-sh-oh** [comment]
Hi @adamczernus,

It appears that you are no longer experiencing the SSLCertVerificationError, which suggests it may have been due to a temporary issue. Did you happen to switch networks?

Regarding the TypeError, this is a minor issue commonly encountered in Python when attempting to call an instance method of a class without providing the instance itself as the first argument. **In plain words, always remember to create an instance of the `collect` class before using any of its method (e.g. `.submission_by_keyword()`, `.comment_from_submission()`, `.subreddit_comment()`)!**  

```python
# Import the collect class from the redditharbor package
from redditharbor.dock.pipeline import collect

# Create an instance of the collect class
collect = collect(reddit_client=reddit_client, supabase_client=supabase_client, db_config=db_config)

# Fetch Submission IDs 
... 

# Call the method with the instance provided
collect.comment_from_submission(submission_ids=submission_ids, level=None)
```

Following these steps should resolve the TypeError issue. Let me know if you encounter any further difficulties or the issue is finally resolved!

**Comment by adamczernus** [comment]
Hello @nick-sh-oh,

Thank you for your help, I was able to collect the comments. I was on university wifi when I had teh SSL erro, so that may have been the issue.

Thanks!
Adam
